/*
 * This source file was generated by the Gradle 'init' task
 */
package digiframe;

import digiframe.frames.AppWindow;

public class App {

    public static void main(String[] args) {
        AppWindow appWindow = new AppWindow();
        appWindow.show();
    }
}
