/*
 * This source file was generated by the Gradle 'init' task
 */
package digiframe;

//import digiframe.window.AppWindow;


public class App {

    public static void main(String[] args) {
        System.out.println("Hello and welcome to DigiFrame!");

        //AppWindow appWindow = new AppWindow();
    }
}
